xtts_model_path: models/xtts/milei
xtts_model_config: models/xtts/milei/config.json
xtts_speaker_wav: models/xtts/milei/reference.wav
xtts_model_temperature: 0.8
xtts_length_penalty: 1.0
xtts_repetition_penalty: 5.0
xtts_top_k: 50
xtts_top_p: 0.85
xtts_speed: 1.0
xtts_num_beams: 1
language: es
rvc_model_pth: models/rvc/milei/rvc_model.pth
rvc_model_index: models/rvc/milei/rvc_model.index
rvc_index_rate: 0.75
rvc_pitch_change: 1
whisper_model: large-v2
whisper_sample_rate: 16000
energy_threshold: 1000
record_timeout: 2
phrase_timeout: 3
pause_threshold: 2
device: cuda
output_file: None
